version: "3.8"

# Development overrides
services:
  gateway:
    volumes:
      - ./services/gateway:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"

  llm_worker:
    volumes:
      - ./services/workers/llm_worker:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  blender_worker:
    volumes:
      - ./services/workers/blender_worker:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG

  # Development tools
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    profiles:
      - dev
