app = "dynasty-os"
primary_region = "us-west1"

[build]
  builder = "python"
  buildCommand = "pip install -r services/gateway/requirements.txt"

[deploy]
  startCommand = "uvicorn services.gateway.main:app --host 0.0.0.0 --port $PORT"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  PYTHON_VERSION = "3.11"