-- Dynasty PropertyOS portfolio scoring artifacts.
-- One current score per property per user, regenerated by batch analysis.

create table if not exists dynasty.deal_scores (
  id text primary key,
  property_id text not null references dynasty."Property"(id) on delete cascade,
  user_id text not null references dynasty."User"(id) on delete cascade,
  deal_score integer not null,
  risk_score integer not null,
  arv_confidence integer not null,
  capital_score integer not null,
  strategy text not null,
  decision text not null,
  score_bucket text not null,
  reasons jsonb not null default '[]',
  inputs jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, property_id)
);

create index if not exists deal_scores_property_id_idx on dynasty.deal_scores(property_id);
create index if not exists deal_scores_user_id_idx on dynasty.deal_scores(user_id);
create index if not exists deal_scores_user_decision_idx on dynasty.deal_scores(user_id, decision);
create index if not exists deal_scores_user_score_bucket_idx on dynasty.deal_scores(user_id, score_bucket);
create index if not exists deal_scores_user_deal_score_idx on dynasty.deal_scores(user_id, deal_score);

-- Supabase/public variant:
--
-- create table public.deal_scores (
--   id uuid primary key default gen_random_uuid(),
--   property_id uuid not null references public.properties(id) on delete cascade,
--   user_id uuid not null references auth.users(id) on delete cascade,
--   deal_score integer not null,
--   risk_score integer not null,
--   arv_confidence integer not null,
--   capital_score integer not null,
--   strategy text not null,
--   decision text not null,
--   score_bucket text not null,
--   reasons jsonb not null default '[]',
--   inputs jsonb not null default '{}',
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   unique (user_id, property_id)
-- );
--
-- alter table public.deal_scores enable row level security;
--
-- create policy "Users can manage their own deal scores"
-- on public.deal_scores for all
-- using (auth.uid() = user_id)
-- with check (auth.uid() = user_id);
