import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { readAutomationBody, requireAutomationAuth } from '@/lib/automation-auth'
import { campaignTypeLabel, generateCampaignArtifact } from '@/lib/campaign-engine/generate-campaign-artifact'

export const dynamic = 'force-dynamic'

export async function POST(request: Request) {
  const auth = await requireAutomationAuth(request)
  if (!auth.ok) return auth.response

  const body = await readAutomationBody(request)
  const campaignType = String(body.campaignType ?? 'ALL')
  const requestedLimit = body.limit === 'all' ? 0 : Number(body.limit ?? 250)
  const take = requestedLimit > 0 ? Math.min(5000, requestedLimit) : undefined
  const includeSkip = Boolean(body.includeSkip ?? false)

  const where = {
    userId: auth.userId,
    status: 'OPEN',
    ...(campaignType !== 'ALL' ? { actionType: campaignType } : {}),
    ...(!includeSkip && campaignType === 'ALL' ? { actionType: { not: 'SKIP' } } : {}),
  }

  const queueItems = await prisma.leadActionQueue.findMany({
    where,
    orderBy: [{ priority: 'desc' }, { nextActionDate: 'asc' }, { updatedAt: 'desc' }],
    ...(take ? { take } : {}),
    include: {
      property: {
        select: {
          address: true,
          city: true,
          state: true,
          zip: true,
          propertyType: true,
          bedrooms: true,
          bathrooms: true,
          sqft: true,
          lotSize: true,
          currentValue: true,
          arv: true,
          contactLinks: {
            where: { status: 'active' },
            take: 1,
            include: {
              contact: { select: { name: true, phone: true, email: true, company: true } },
            },
          },
          ownerIntelligenceArtifacts: {
            take: 1,
            orderBy: { updatedAt: 'desc' },
            select: {
              ownerName: true,
              mailingAddress: true,
              ownerType: true,
              absenteeOwner: true,
              yearsOwned: true,
              equityEstimate: true,
              vacancyIndicator: true,
              contactConfidence: true,
              phones: true,
              emails: true,
            },
          },
        },
      },
      dealScore: {
        select: {
          dealScore: true,
          riskScore: true,
          strategy: true,
          decision: true,
          scoreBucket: true,
        },
      },
    },
  })

  if (queueItems.length === 0) {
    return NextResponse.json({ status: 'empty', engine: 'campaign_engine', generated: 0, batchIds: [], automation: true })
  }

  const grouped = new Map<string, typeof queueItems>()
  for (const item of queueItems) {
    grouped.set(item.actionType, [...(grouped.get(item.actionType) ?? []), item])
  }

  const batchIds: string[] = []
  let generated = 0

  for (const [type, items] of grouped.entries()) {
    const batch = await prisma.campaignBatch.create({
      data: {
        userId: auth.userId,
        campaignType: type,
        name: `${campaignTypeLabel(type)} - ${new Date().toLocaleDateString('en-US')}`,
        status: 'READY',
        scheduledDate: new Date(),
        totalItems: items.length,
        notes: `Generated by automation from ${items.length} ${campaignTypeLabel(type)} lead action queue item${items.length === 1 ? '' : 's'}.`,
      },
    })

    await prisma.campaignItem.createMany({
      data: items.map((item) => ({
        batchId: batch.id,
        queueItemId: item.id,
        propertyId: item.propertyId,
        userId: auth.userId,
        campaignType: type,
        priority: item.priority,
        artifact: generateCampaignArtifact({
          id: item.id,
          propertyId: item.propertyId,
          actionType: item.actionType,
          priority: item.priority,
          reason: item.reason,
          property: item.property,
          dealScore: item.dealScore,
        }),
      })),
    })

    batchIds.push(batch.id)
    generated += items.length
  }

  const totalItems = await prisma.campaignItem.count({ where: { userId: auth.userId } })
  return NextResponse.json({
    status: 'complete',
    engine: 'campaign_engine',
    generated,
    batchIds,
    totalItems,
    automation: true,
  })
}
